from pathlib import Path
from html import escape
from survey import questionnaire
ROOT=Path(__file__).resolve().parent
OUT=ROOT.parent/'dist'
OUT.mkdir(exist_ok=True)
NAV=[('Home','/'),('VRS Issues','/issues/'),('Petition','/petition/'),('Interpreters','/interpreters/'),('Community','/community/'),('CRTC','/crtc/'),('CAV','/cav/'),('Evidence','/evidence/'),('Resources','/resources/'),('Updates','/updates/'),('About','/about/')]
def links(path):
 return ''.join(f'<a href="{url}"'+(' aria-current="page"' if url==path else '')+f'>{label}</a>' for label,url in NAV)
def card(k,title,text,url=None,label='Explore'):
 return f'<article class="card"><p class="eyebrow">{k}</p><h2>{title}</h2><p>{text}</p>'+ (f'<a class="text-link" href="{url}">{label} <span aria-hidden="true">↗</span></a>' if url else '')+'</article>'
def page(path,title,eyebrow,heading,intro,body):
 if path == '/petition/':
  body = '<aside class="status"><div><strong>Who this petition is for</strong><p>This user petition and its questionnaire are intended only for people registered as users with Canada VRS. Everyone may read the public information.</p><p>An XCTVRS account is not the same as registration with Canada VRS. This preview does not verify eligibility or collect signatures. Do not provide your Canada VRS password or account documents here.</p><p>Interpreter participation has its own separate petition draft.</p><a class="text-link" href="/interpreters/">View the interpreter petition</a></div></aside>' + body
  body = body.replace('<a class="button" href="#statement">', '<a class="button secondary" href="#platform-questions">Explore platform questions</a><a class="button" href="#statement">', 1)
  body += questionnaire()
 layout = 'petition' if path == '/petition/' else 'standard'
 chapters = '<nav class="chapter-nav" aria-label="Petition sections"><span>XCTVRS / PETITION</span><a href="#statement">01 · The statement</a><a href="#support">02 · Participation</a><a href="#platform-questions">03 · Your experience</a></nav>' if path == '/petition/' else ''
 canadian = '<div class="canadian-detail"><svg class="maple" viewBox="0 0 64 70" aria-hidden="true"><path d="M30 66l1-18-18 3 3-9L4 31l8-2-2-12 13 9-2-16 7 4L32 2l5 12 7-4-3 16 13-9-2 12 8 2-12 11 3 9-18-3 1 18z"></path></svg><span>Independent voices · Canada</span></div>'
 canonical='https://xctvrs.ca'+path
 h=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><title>{escape(title)} | XCTVRS</title><meta name="description" content="{escape(intro,quote=True)}"><link rel="canonical" href="{canonical}"><link rel="stylesheet" href="/assets/site.css"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"></head><body data-design="heritage" data-page="{layout}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-top"><a class="brand" href="/">XCT<span>VRS</span><small>Independent advocacy · Canada</small></a><span class="header-note">Clear evidence. Better communication.</span></div><nav class="desktop-nav" aria-label="Main navigation">{links(path)}</nav><details class="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation">{links(path)}</nav></details></header><main id="main">{chapters}<section class="page-hero">{canadian}<p class="eyebrow">{eyebrow}</p><h1>{heading}</h1><p class="lead">{intro}</p></section>{body}</main><footer><div><a class="brand" href="/">XCT<span>VRS</span></a><p>Independent Canada VRS advocacy.<br>Not affiliated with CAV, Canada VRS, or the CRTC.</p></div><div class="footer-links"><a href="/about/">About this project</a><a href="/petition/">Petition draft</a><a href="/contact/">Participation status</a><a href="https://dun360.com/">DUN360 · Public voice</a><a href="https://xct.guru/">XCT.Guru · Technology</a></div></footer></body></html>'''
 dest=OUT/('index.html' if path=='/' else path.strip('/')+'/index.html')
 dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(h)
page('/','Canada VRS advocacy','The independent VRS advocacy hub','Better communication.<br><span>Clearer accountability.</span>','One place for Canada VRS service-quality concerns, public advocacy, community participation plans, and relevant CRTC and CAV information.',
'''<div class="hero-actions"><a class="button" href="/issues/">Explore VRS issues</a><a class="button secondary" href="/petition/">Read the petition draft</a></div><aside class="status"><span class="status-dot" aria-hidden="true"></span><div><strong>Petition in development</strong><p>The wording is a draft. Signing is not open, and launch or submission has not been confirmed.</p></div></aside><section class="section"><div class="section-heading"><p class="eyebrow">Understand · review · participate</p><h2>A shared focus on better VRS</h2><p>Start with the issues, see what the draft asks for, and follow the project as reviewed material becomes available.</p></div><div class="grid three">'''+
card('01 / Service quality','Understand the issues','Platform reliability, interpreter handoffs, video-mail quality, and complaint transparency.','/issues/','Explore the focus areas')+
card('02 / Public action','Review the proposed petition','A call for measurable improvement, clearer accountability, and evidence-led review of platform and provider performance.','/petition/','Read the draft')+
card('03 / The record','Follow the evidence','A place for reviewed records with clear sources, dates, and document status. Private correspondence is not published automatically.','/evidence/','How evidence is handled')+
'''</div></section><section class="section feature"><div><p class="eyebrow">Community, built with care</p><h2>One VRS community.<br>One place to take part.</h2><p>Accounts, surveys, experience submissions, and independent working groups are planned for XCTVRS. Public information stays readable without signing in.</p><a class="text-link" href="/community/">See the participation plans ↗</a></div><div class="principles"><p><strong>Independent</strong><span>A project for advocacy, not an official representative of all VRS users.</span></p><p><strong>Clear about status</strong><span>A draft is a draft. A sent email is not automatically a formal filing.</span></p><p><strong>One maintained source</strong><span>VRS petitions, participation, and records belong here.</span></p></div></section>''')
page('/issues/','VRS Issues','Focus areas','Reliability matters.<br><span>So does accountability.</span>','These are the service-quality questions this advocacy project aims to examine. They are areas for inquiry, not findings against a provider.',
'<section class="grid two">'+card('Platform','Reliable connections','How can interruptions and disconnections be documented, investigated, and reduced? What information helps distinguish a platform issue from other causes?')+card('Handoffs','Continuity during interpreter changes','How can calls remain connected during breaks, shift changes, and other handoffs? Technical reliability and interpreter-quality concerns need distinct review paths.')+card('Video mail','Clear, usable video messages','How can video-mail quality be assessed consistently? Reports of blur or pixelation need supporting examples before their technical cause is identified.')+card('Complaints','A clearer route to resolution','How can users see that a report was received, where it was routed, its current status, and what was done? This includes questions about the 9050 support structure.')+card('Provider accountability','Performance that can be evaluated','What evidence should be used to review platform and vendor performance, corrective action, and potential alternatives?')+card('Quality of service','Measurable improvement','What useful measures can show whether service is improving? Proposed metrics must be distinguished from measured results and existing requirements.')+'</section><div class="hero-actions"><a class="button" href="/petition/">Read the proposed requests</a><a class="button secondary" href="/resources/">Official resources</a></div>')
requests=['Measurable reporting of platform reliability and service interruptions.','Better transparency when complaints and technical incidents are reported.','A clear distinction between technical platform problems and interpreter-quality concerns.','Appropriate accountability for platform and vendor performance, including evidence-led consideration of better-performing alternatives.','Meaningful reporting on corrective action and service improvement.','Continued modernization informed by user experience and measurable service performance.']
page('/petition/','Petition draft','Public advocacy · draft','Support Fair and Accountable VRS Access','This petition page is focused on fair access, service reliability, public accountability, and meaningful improvement in Video Relay Service systems. The goal is to create a clear public statement that supporters can understand, share, and strengthen.',
'<aside class="status"><span class="badge">DRAFT</span><div><strong>Public launch and submission unconfirmed</strong><p>There is no signing form or published supporter count. Final wording and a participation process must be approved before signing opens.</p></div></aside><div class="hero-actions"><a class="button" href="#statement">Read Statement</a><a class="button secondary" href="#support">Support This Petition</a></div><section class="grid three"><article class="card"><h2>Access</h2><p>Communication access must be dependable, not inconsistent.</p></article><article class="card"><h2>Accountability</h2><p>Service concerns should be documented, addressed, and measured.</p></article><article class="card"><h2>Visibility</h2><p>The real impact on users should not stay hidden or minimized.</p></article></section><section id="statement" class="section prose"><h2>Proposed statement</h2><p>We call for fair, reliable, and respectful access to Video Relay Service for the people who depend on it in everyday life. When communication access becomes unstable, delayed, poorly supported, or difficult to trust, the impact goes far beyond inconvenience. It affects safety, independence, employment, family connection, and equal participation.</p><p>This petition exists to document those concerns clearly, raise public awareness, and support practical improvements that can be measured over time. The request is simple: improve service reliability, strengthen accountability, and treat communication access as essential.</p><p>We believe the people who rely on VRS deserve a system that reflects consistency, transparency, and respect. This page is a starting point for building that record.</p></section><section class="grid two"><article class="card"><h2>What this petition is asking for</h2><ul><li>More dependable VRS service access</li><li>Clearer accountability when service issues occur</li><li>Better visibility into the impact on users</li><li>Stronger response standards and follow-up</li><li>A more respectful and practical advocacy record</li></ul></article><article class="card"><h2>Why this matters</h2><ul><li>Communication access affects real daily life</li><li>Unresolved service gaps can create wider harm</li><li>Public awareness is needed beyond private complaints</li><li>Consistent documentation helps support real change</li></ul></article></section><section id="support" class="section feature"><div><p class="eyebrow">Before signing opens</p><h2>A clear process comes first.</h2><p>Final wording, privacy choices, and the support process need review before this project collects signatures. Reading this draft does not register your support or create an account.</p></div><a class="button secondary" href="/updates/">Follow project updates</a></section>')
page('/community/','Community','Participation plans','A place for VRS users<br><span>to participate.</span>','XCTVRS is the planned home for VRS advocacy participation. Public pages remain open to read without an account.',
'<section class="grid three">'+card('Planned','One XCTVRS account','Accounts may support petition participation, preferences, topic updates, and approved community activities. Account registration is not available yet.')+card('Planned','Experiences and surveys','A future process will explain what is collected, how it is used, and what you choose to share publicly before accepting stories, video, or survey responses.')+card('Future','Independent working groups','Groups may form around a location, service issue, or regulatory activity when there is a real need. No Montreal or other regional group is being announced here.')+'</section><section class="section prose"><h2>Participation does not mean official representation</h2><p>A participant, contributor, or coordinator does not automatically represent all Deaf people or all VRS users. Any future group will explain its purpose, membership, and decision-making arrangements.</p><h2>Public reading stays open</h2><p>You will not need an account simply to read advocacy information, petition wording, public records, or project updates.</p></section>')
page('/crtc/','CRTC information','Regulatory information','CRTC information,<br><span>with clear document status.</span>','This area is intended for reviewed CRTC-related information and correspondence. It is not an official CRTC website.',
'<section class="grid two">'+card('Official source','Video Relay Service','Use the CRTC’s own VRS information page for published policy and service information.','https://crtc.gc.ca/eng/phone/acces/rela.htm','Open the CRTC VRS page')+card('Archive status','Records awaiting review','No private complaint reference, correspondence, hearing date, or claimed filing is published here. Original documents and their status need review before being added.')+'</section><section class="section prose"><h2>Correspondence and filings are different</h2><p>A draft, a sent email, a received reply, and a formal filing describe different events. Future records will state their source and known status. The presence of a document here will not, by itself, mean it was filed or accepted.</p><a class="text-link" href="/evidence/">Review the evidence approach ↗</a></section>')
page('/cav/','CAV information','Correspondence and accountability','CAV information,<br><span>organized around the record.</span>','A dedicated area for reviewed correspondence and information relating to CAV and Canada VRS.',
'<section class="grid two">'+card('Planned record','Correspondence','Reviewed records will identify the date, source, summary, and whether an item is a draft, sent, received, acknowledged, or undelivered.')+card('Review pending','Originals before publication','Private emails and screenshots are not posted here. Exact wording, dates, personal information, and publication approval must be reviewed first.')+'</section><section class="section prose"><h2>Questions for clearer accountability</h2><p>Complaint receipt, routing, follow-up, technical accountability, and service-quality reporting are among the project’s focus areas. These questions do not substitute for the contents of an original response.</p><a class="text-link" href="/issues/">Explore the advocacy questions ↗</a></section>')
page('/evidence/','Evidence','Sources and status','Evidence you can<br><span>understand in context.</span>','This will be the central home for reviewed VRS records. No private evidence or unverified scorecards are published here.',
'<section class="grid three">'+card('Source','Where a statement comes from','Personal experience, correspondence, opinion, proposals, and official records will be identified separately.')+card('Status','What actually happened','Draft, Sent, Received, Acknowledged, Bounced / Undelivered, and Status Unconfirmed will describe the known document status without implying a formal filing.')+card('Review','What can be shared','Dates, original wording, authorship, redactions, and publication approval are checked before a record appears publicly.')+'</section><section class="section prose"><h2>Assessments are not official statistics</h2><p>Any future scorecard will need a stated methodology and supporting material. Proposed performance measures are recommendations unless an identified source establishes them as existing requirements or measured results.</p><h2>Archive status</h2><p>Public documents will be added after review. There are no private-record downloads on this page.</p></section>')
page('/resources/','Resources','Read from the source','Official references.<br><span>A clearer starting point.</span>','Use original sources alongside this independent advocacy project. These links are references, not endorsements of XCTVRS.',
'<section class="grid two">'+card('CRTC','Video Relay Service','The CRTC’s information hub for VRS and related policy.','https://crtc.gc.ca/eng/phone/acces/rela.htm','Read the official overview')+card('CRTC · ASL','VRS policy in ASL','The CRTC’s ASL summary of its 2025 VRS policy.','https://web.crtc.gc.ca/eng/phone/acces/rela/pllsrrela/','View the ASL resource')+card('CRTC','Accessible phone service policies','An index of related policies, decisions, and orders.','https://crtc.gc.ca/eng/phone/acces/pol.htm','Browse official records')+card('XCTVRS','Understanding document status','How this project distinguishes experiences, records, drafts, and proposals.','/evidence/','Read the evidence approach')+'</section>')
page('/updates/','Updates','Project updates','Follow what changes.<br><span>Know what is still planned.</span>','Updates about the XCTVRS website and advocacy project. A website update is not a regulatory outcome or petition submission.',
'<section class="section prose"><p class="eyebrow">Website update · September 9, 2026</p><h2>One home for Canada VRS advocacy</h2><p>XCTVRS now brings the project’s issue overview, petition draft, community plans, and record-review approach into one site. DUN360 directs VRS advocacy visitors here; XCT.Guru focuses on the technical project.</p><h2>Current participation status</h2><p>Signing, account registration, surveys, and working groups are not open. The petition remains a draft, and private records remain unpublished.</p></section>')
page('/about/','About XCTVRS','Independent by design','VRS advocacy.<br><span>One organized place.</span>','XCTVRS is an independent Canada VRS advocacy platform focused on service quality, user experience, accountability, transparency, community participation, and relevant regulatory activity.',
'<section class="section prose"><h2>Our purpose</h2><p>Make concerns easier to understand, proposals easier to review, and relevant records easier to follow. Community participation will be added as a clear and appropriate process becomes available.</p><h2>Independent advocacy</h2><p>XCTVRS does not officially represent every Deaf person or VRS user in Canada. It is not CAV, Canada VRS, the CRTC, or an official regulatory body.</p><h2>Three sites, distinct roles</h2><p><a href="https://dun360.com/">DUN360</a> is the broader public voice for Deaf advocacy, awareness, stories, and media. <a href="https://xct.guru/">XCT.Guru</a> is the professional and technical platform. XCTVRS is the central home for this project’s VRS advocacy and future participation.</p><p>The technical development interests presented on XCT.Guru are distinct from the evidence and advocacy record here. They do not establish that a proposed platform is proven or a provider is superior.</p></section>')
page('/contact/','Participation status','Contact and participation','A clear route<br><span>before collecting information.</span>','Public submissions, account registration, and petition signing are not open on this site yet.',
'<section class="section prose"><h2>What you can do now</h2><p>Read the issue overview, review the petition draft, and explore the official resources. An approved contact or participation process will be explained here before personal information is collected.</p><div class="hero-actions"><a class="button" href="/petition/">Read the draft</a><a class="button secondary" href="/resources/">Explore resources</a></div></section>')
page('/interpreters/','Interpreter petition draft','Interpreters · separate petition draft','A separate voice for interpreters.','This proposed petition is for interpreters only. It provides a separate place to develop concerns and requests about the Canada VRS technical platform, without combining interpreter participation with the registered-user petition.','<aside class="status"><span class="badge">DRAFT</span><div><strong>Not open for signatures or confidential submissions</strong><p>No secure intake is available on this page. Do not send private call details, client identities, employer records, or confidential workplace information through this preview.</p></div></aside><section class="section prose"><h2>Proposed interpreter statement</h2><p>We ask for a reliable technical platform that supports clear signed communication and continuity during calls and interpreter handoffs. We ask for an appropriate process for reporting technical problems and receiving meaningful follow-up.</p><p>This draft focuses on platform operation and technical accountability. It does not assess individual interpreters or claim to represent all interpreters or a professional association.</p></section><section class="section prose"><h2>Privacy before participation</h2><p>A future process should keep identities and individual contributions private by default, separate contact details from publishable material, and limit access to authorized reviewers. These protections must be implemented before intake opens; this draft is not a guarantee of anonymity or confidentiality.</p></section><section class="section prose"><h2>Choose what may be shared, and with whom</h2><p>Possible recipients for reviewed material are an independent ad hoc working group, the CRTC, or CASLI. Before any sharing, contributors should see the exact material, intended recipient, and identifying details that would be disclosed, and give specific consent.</p><p>No group or recipient is confirmed by this page. Nothing is automatically forwarded. Signing a petition would not, by itself, authorize sharing a private account or publishing a name.</p><p>Any public filing would need a separate review of what becomes public before the contributor agrees to that route. No petition or testimony is described here as sent, filed, or acknowledged.</p></section><div class="hero-actions"><a class="button secondary" href="/petition/">Return to the registered-user petition</a></div>')
(OUT/'404.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | XCTVRS</title><link rel="stylesheet" href="/assets/site.css"><main><h1>Page not found</h1><p>This address does not have a published page.</p><a class="button" href="/">Return to XCTVRS</a></main></html>')
print('Built 12 XCTVRS pages and a 404 page; no records, accounts, signature counts, or response collection included.')

from localize import localize
localize(OUT, ROOT)

import shutil
shutil.copytree(ROOT.parent / "assets", OUT / "assets", dirs_exist_ok=True)
from fingerprint import fingerprint
fingerprint(OUT)
